### ISSUE TITLE
Get new products on the oa.works website

### ISSUE THREAD

**Issue by JosephMcArthur** [oaworks/oa-works#118]
While these products are not yet easy to use / sign up for, they are still products and it was an oversight on my part not to ask for their inclusion on these pages ahead of release. Just getting to addressing that now after a busy week or two.

## TODO

- [x] Add OAreport as featured product
- [x] @sssoz can you advise if you see having 4 featured as a problem?
- [x] Add OAsupport as product
- [x] Add OAreport / OAsupport descriptions & labels - @JosephMcArthur 
- [x] Consider (discuss?) how to handle logos - @sssoz 

I've [started a PR](https://github.com/oaworks/oa-works/pull/119) with the values we have to hand now (mainly so I could have the above checklist be accurate).

Also, for the avoidance of doubt, I don't consider is an urgent thing to do.

cc @jorlowitz

**Comment by sssoz** [comment]
Re: building vs managing, I think that in this case creating a PR for me was not necessary... I can do it myself quickly, and my own way / without formatting issues, once I pick this issue up and we figure out what exactly we want to display.

**Comment by JosephMcArthur** [comment]
Yup totally fair. How's about we close the PR rather than having me try and fix it?

**Comment by sssoz** [comment]
Sure

**Comment by sssoz** [comment]
>  @sssoz can you advise if you see having 4 featured as a problem?

We can display four. Just need to fiddle a bit around stylesheets, the cards are quite large. 

> Consider (discuss?) how to handle logos

Removed them. We’ll be using plain text to keep things simple, as we did for OAreport and OAsupport.

**Comment by JosephMcArthur** [comment]
Kay, thanks!

> Add OAreport / OAsupport descriptions & labels

Is now ticked. Have you drafted copy for those?

**Comment by sssoz** [comment]
I did but haven't pushed them! Can't do it until tomorrow though

**Comment by sssoz** [comment]
See https://docs.google.com/document/d/1diVEJFrjc69RJzGVVfmvHp1DIHA91pyGjet8do2Juwg/edit?usp=sharing

**Comment by sssoz** [comment]
@JosephMcArthur See https://dev.oa.works/ 

It’s quite small, some layout changes will be needed eventually but I think it’ll do for now -- the info and links are there. 

When you’re OK with it, I will merge to `main`.

**Comment by JosephMcArthur** [comment]
Approved! Go go go :)

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by sssoz** [comment]
Done and on oa.works

**Comment by JosephMcArthur** [comment]
Thanks Sophy! Great to have these up.

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur

**Comment by jorlowitz** [comment]
Just curious if we're going to also update the purple menu and footer with
products 4 and 5?

Cheers,

Jake Orlowitz
*Founder of The Wikipedia Library*
*Seeker of well people and sane societies*
*Lead at WikiBlueprint*
  me: jakeorlowitz.com
  media: @jakeorlowitz <http://twitter.com/jakeorlowitz>
  blueprint: wikiblueprint.com
  book: welcometothecircle.net
